import React from "react";
import Head from "next/head";

import Nav from "../components/nav";
import Cursor from "../components/cursor";

import Descriptions from "sections/descriptions";
import Splash from "sections/splash";
import Locations from "sections/locations";
import Faq from "sections/faq/faq";

export default function Home() {
    return (
        <>
            <Head>
                <title>CUSEC 2022</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>

            <Cursor></Cursor>
            
            <Nav></Nav>

            <main className="flex flex-col justify-center items-center min-h-screen">
                <Splash />
                <Locations />
                <Descriptions />
                <Faq />
            </main>
        </>
    );
}
