import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components';
import { useEffect, useState } from 'react';

export default function Home() {
  useEffect(() => {
    window.addEventListener("scroll", function() {
      let color = '#';
      for (let i = 0; i < 6; i++){
          const random = Math.random();
          const bit = (random * 16) | 0;
          color += (bit).toString(16);
      };
      this.document.body.style.backgroundColor = color;
    }, [])
  });

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to cusec.net
        </h1>
      </main>
    </div>
  )
}
